/*
USE master

IF EXISTS(SELECT * FROM SYS.databases WHERE name = 'AGENDA')
	DROP DATABASE AGENDA

CREATE DATABASE AGENDA
*/

USE AGENDA

CREATE TABLE USUARIO
(
	COD_USUARIO INT PRIMARY KEY IDENTITY,
	NOME_USUARIO VARCHAR(20), 
	PWD_USUARIO VARCHAR(100), 
	ADM_USUARIO CHAR(1) CHECK (ADM_USUARIO IN ('S', 'N'))
)

CREATE TABLE TIPO_CONTATO
(
	COD_TIPO_CONTATO INT PRIMARY KEY IDENTITY, 
	DESCRICAO_TIPO_CONTATO VARCHAR(50) UNIQUE
)

CREATE TABLE CONTATO
(
	COD_CONTATO INT PRIMARY KEY IDENTITY, 
	NOME_CONTATO VARCHAR(50), 
	EMAIL_CONTATO VARCHAR(100), 
	SITE_CONTATO VARCHAR(MAX), 
	DDD_CONTATO CHAR(2), 
	FONE_CONTATO CHAR(8), 
	CELULAR_CONTATO CHAR(8),
	COD_TIPO_CONTATO INT NOT NULL REFERENCES TIPO_CONTATO
)

--INSERT INTO USUARIO
--VALUES ('ADMIN', 'ADMIN', 'S')

GO

CREATE PROC USP_LOGAR
	@NOME_USUARIO VARCHAR(20), 
	@PWD_USUARIO VARCHAR(100)	
AS
	SET NOCOUNT ON

	SELECT *
	FROM USUARIO
	WHERE NOME_USUARIO = @NOME_USUARIO
		AND PWD_USUARIO = @PWD_USUARIO 
GO
	
SELECT * FROM USUARIO

EXEC USP_LOGAR 'ADMIN', 'yQ0EqppXuB3bgMaIP1/I0w=='
EXEC USP_LOGAR 'USUARIO', 'ukyPPDtuZ54eJTdnOrrR2w=='
