//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteWCF.ProxyUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioModel", Namespace="http://schemas.datacontract.org/2004/07/BLL_DAL.Model")]
    [System.SerializableAttribute()]
    public partial class UsuarioModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char AdmUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PwdUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char AdmUsuario {
            get {
                return this.AdmUsuarioField;
            }
            set {
                if ((this.AdmUsuarioField.Equals(value) != true)) {
                    this.AdmUsuarioField = value;
                    this.RaisePropertyChanged("AdmUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodUsuario {
            get {
                return this.CodUsuarioField;
            }
            set {
                if ((this.CodUsuarioField.Equals(value) != true)) {
                    this.CodUsuarioField = value;
                    this.RaisePropertyChanged("CodUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuario {
            get {
                return this.NomeUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeUsuarioField, value) != true)) {
                    this.NomeUsuarioField = value;
                    this.RaisePropertyChanged("NomeUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PwdUsuario {
            get {
                return this.PwdUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.PwdUsuarioField, value) != true)) {
                    this.PwdUsuarioField = value;
                    this.RaisePropertyChanged("PwdUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUsuario.IUsuario")]
    public interface IUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Inserir", ReplyAction="http://tempuri.org/IUsuario/InserirResponse")]
        void Inserir(TesteWCF.ProxyUsuario.UsuarioModel usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Alterar", ReplyAction="http://tempuri.org/IUsuario/AlterarResponse")]
        void Alterar(TesteWCF.ProxyUsuario.UsuarioModel usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Excluir", ReplyAction="http://tempuri.org/IUsuario/ExcluirResponse")]
        void Excluir(TesteWCF.ProxyUsuario.UsuarioModel usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Consultar", ReplyAction="http://tempuri.org/IUsuario/ConsultarResponse")]
        TesteWCF.ProxyUsuario.UsuarioModel[] Consultar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ConsultarCodUsuario", ReplyAction="http://tempuri.org/IUsuario/ConsultarCodUsuarioResponse")]
        TesteWCF.ProxyUsuario.UsuarioModel ConsultarCodUsuario(TesteWCF.ProxyUsuario.UsuarioModel usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Logar", ReplyAction="http://tempuri.org/IUsuario/LogarResponse")]
        TesteWCF.ProxyUsuario.UsuarioModel Logar(TesteWCF.ProxyUsuario.UsuarioModel usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioChannel : TesteWCF.ProxyUsuario.IUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioClient : System.ServiceModel.ClientBase<TesteWCF.ProxyUsuario.IUsuario>, TesteWCF.ProxyUsuario.IUsuario {
        
        public UsuarioClient() {
        }
        
        public UsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Inserir(TesteWCF.ProxyUsuario.UsuarioModel usuario) {
            base.Channel.Inserir(usuario);
        }
        
        public void Alterar(TesteWCF.ProxyUsuario.UsuarioModel usuario) {
            base.Channel.Alterar(usuario);
        }
        
        public void Excluir(TesteWCF.ProxyUsuario.UsuarioModel usuario) {
            base.Channel.Excluir(usuario);
        }
        
        public TesteWCF.ProxyUsuario.UsuarioModel[] Consultar() {
            return base.Channel.Consultar();
        }
        
        public TesteWCF.ProxyUsuario.UsuarioModel ConsultarCodUsuario(TesteWCF.ProxyUsuario.UsuarioModel usuario) {
            return base.Channel.ConsultarCodUsuario(usuario);
        }
        
        public TesteWCF.ProxyUsuario.UsuarioModel Logar(TesteWCF.ProxyUsuario.UsuarioModel usuario) {
            return base.Channel.Logar(usuario);
        }
    }
}
