//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumidorWS.ProxyPessoa {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pessoa", Namespace="http://50minutos.com.br/exemplos/")]
    [System.SerializableAttribute()]
    public partial class Pessoa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodPessoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomePessoaField;
        
        private char SexoPessoaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodPessoa {
            get {
                return this.CodPessoaField;
            }
            set {
                if ((this.CodPessoaField.Equals(value) != true)) {
                    this.CodPessoaField = value;
                    this.RaisePropertyChanged("CodPessoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomePessoa {
            get {
                return this.NomePessoaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomePessoaField, value) != true)) {
                    this.NomePessoaField = value;
                    this.RaisePropertyChanged("NomePessoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public char SexoPessoa {
            get {
                return this.SexoPessoaField;
            }
            set {
                if ((this.SexoPessoaField.Equals(value) != true)) {
                    this.SexoPessoaField = value;
                    this.RaisePropertyChanged("SexoPessoa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://50minutos.com.br/exemplos/", ConfigurationName="ProxyPessoa.WSPessoaSoap")]
    public interface WSPessoaSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://50minutos.com.br/exemplos/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://50minutos.com.br/exemplos/HelloWorld", ReplyAction="*")]
        ConsumidorWS.ProxyPessoa.HelloWorldResponse HelloWorld(ConsumidorWS.ProxyPessoa.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://50minutos.com.br/exemplos/Somar", ReplyAction="*")]
        int Somar(int x, int y);
        
        // CODEGEN: Generating message contract since element name SelecionarResult from namespace http://50minutos.com.br/exemplos/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://50minutos.com.br/exemplos/Selecionar", ReplyAction="*")]
        ConsumidorWS.ProxyPessoa.SelecionarResponse Selecionar(ConsumidorWS.ProxyPessoa.SelecionarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://50minutos.com.br/exemplos/", Order=0)]
        public ConsumidorWS.ProxyPessoa.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsumidorWS.ProxyPessoa.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://50minutos.com.br/exemplos/", Order=0)]
        public ConsumidorWS.ProxyPessoa.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsumidorWS.ProxyPessoa.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://50minutos.com.br/exemplos/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelecionarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Selecionar", Namespace="http://50minutos.com.br/exemplos/", Order=0)]
        public ConsumidorWS.ProxyPessoa.SelecionarRequestBody Body;
        
        public SelecionarRequest() {
        }
        
        public SelecionarRequest(ConsumidorWS.ProxyPessoa.SelecionarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelecionarRequestBody {
        
        public SelecionarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelecionarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelecionarResponse", Namespace="http://50minutos.com.br/exemplos/", Order=0)]
        public ConsumidorWS.ProxyPessoa.SelecionarResponseBody Body;
        
        public SelecionarResponse() {
        }
        
        public SelecionarResponse(ConsumidorWS.ProxyPessoa.SelecionarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://50minutos.com.br/exemplos/")]
    public partial class SelecionarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumidorWS.ProxyPessoa.Pessoa[] SelecionarResult;
        
        public SelecionarResponseBody() {
        }
        
        public SelecionarResponseBody(ConsumidorWS.ProxyPessoa.Pessoa[] SelecionarResult) {
            this.SelecionarResult = SelecionarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSPessoaSoapChannel : ConsumidorWS.ProxyPessoa.WSPessoaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSPessoaSoapClient : System.ServiceModel.ClientBase<ConsumidorWS.ProxyPessoa.WSPessoaSoap>, ConsumidorWS.ProxyPessoa.WSPessoaSoap {
        
        public WSPessoaSoapClient() {
        }
        
        public WSPessoaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSPessoaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPessoaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPessoaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumidorWS.ProxyPessoa.HelloWorldResponse ConsumidorWS.ProxyPessoa.WSPessoaSoap.HelloWorld(ConsumidorWS.ProxyPessoa.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsumidorWS.ProxyPessoa.HelloWorldRequest inValue = new ConsumidorWS.ProxyPessoa.HelloWorldRequest();
            inValue.Body = new ConsumidorWS.ProxyPessoa.HelloWorldRequestBody();
            ConsumidorWS.ProxyPessoa.HelloWorldResponse retVal = ((ConsumidorWS.ProxyPessoa.WSPessoaSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        public int Somar(int x, int y) {
            return base.Channel.Somar(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumidorWS.ProxyPessoa.SelecionarResponse ConsumidorWS.ProxyPessoa.WSPessoaSoap.Selecionar(ConsumidorWS.ProxyPessoa.SelecionarRequest request) {
            return base.Channel.Selecionar(request);
        }
        
        public ConsumidorWS.ProxyPessoa.Pessoa[] Selecionar() {
            ConsumidorWS.ProxyPessoa.SelecionarRequest inValue = new ConsumidorWS.ProxyPessoa.SelecionarRequest();
            inValue.Body = new ConsumidorWS.ProxyPessoa.SelecionarRequestBody();
            ConsumidorWS.ProxyPessoa.SelecionarResponse retVal = ((ConsumidorWS.ProxyPessoa.WSPessoaSoap)(this)).Selecionar(inValue);
            return retVal.Body.SelecionarResult;
        }
    }
}
